# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

# https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.7"
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"

[prune]
  go-tests = true
  unused-packages = true
